### ISSUE TITLE
System.DmlException: Delete failed

### ISSUE THREAD

**Issue by mchang-r7** [martyychang/sfdc-dml-history#5]
With `AccountMergeResultTrigger` deployed as-is, the following error is encountered when trying to simply delete—not _merge_—an Account record.

> System.DmlException: Delete failed. First exception on row 0 with id 0010U0000034EcsQAE; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, AccountMergeResultTrigger: execution of AfterDelete caused by: System.QueryException: List has no rows for assignment to SObject Class.MergeResultService.getMasterRecord: line 54, column 1 Class.MergeResultService.getMergeResult: line 60, column 1 Trigger.AccountMergeResultTrigger: line 11, column 1: []

**Comment by martyychang** [comment]
I encountered this again trying to create a simple **DML History** app for `delete` operations

**Comment by martyychang** [comment]
Checking records for presence of a master record with `String.isNotBlank((Id)eachRecord.get('MasterRecordId'))` did the trick
